version: "2.2"

services: 
    gambio-shop:
        image: gambio-5-0-1
        build: ./docker/web
        ports: 
            - "80:80"
        volumes: 
            - ./shop:/var/www/html
        depends_on: 
            - "gambio-db"
    
    gambio-db:
        image: mariadb:10.6.0
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        volumes:
            - ./gambio_db_5_0_1:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:5.1.0-apache
        ports: 
            - "8080:80"
        environment: 
            PMA_HOST: gambio-db
        depends_on: 
            - "gambio-db"

volumes: 
    gambio_db_5_0_1:



